### ISSUE TITLE
ProvisionWatcher: replace OperatingState field, add blocking criteria

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/go-mod-core-contracts#111]
The purpose of the OperatingState field was that devices created as a result of ProvisionWatcher matches would initially be either enabled or disabled.
However:
* The Administrative State is more applicable to controlling availability for policy reasons.
* We would like to allow for blacklisting using the ProvisionWatcher mechanism.

So:
1) Define a new enumeration "OnMatch" which defines the action to take when a PW is matched. Available values to be
* IGNORE - matching devices are not added
* LOCK - matching devices to be added in the Locked AdminState
* UNLOCK - matching devices to be added in the Unlocked AdminState
2) Replace the OperatingState field with one of this type.

Device services should then, on discovery of a new device, proceed according to the most restrictive PW that matches on that device.

**EDIT: Finalized ProvisionWatcher design, replacing the above, is here: [https://github.com/edgexfoundry/go-mod-core-contracts/issues/111#issuecomment-517362872](url)**

**Comment by tsconn23** [comment]
Notes from Device Service WG 24-Jun-2019

- Decided to add IGNORE as additional value to AdminState enum.
- Decided to add AdminState property to ProvisionWatcher. This may not exist in a request if an older Device Service is calling a later version of the Core Services, so we need to decide on a default value for this new property.
- Decided default value will be LOCKED.

**Comment by tonyespy** [comment]
I agree with you that AdminState makes more sense than OpState, as you may indeed want to add devices but not have them usable right away. Regarding OpState, I think the assumption is that since the device was discovered and returned to the SDK as part of a ScanResults list by a ProtocolDriver, that the device is in a working state, so what's the use case for being able to specify OpState=disabled? 

As far as OnMatch goes, I would suggest instead of adding a new field and removing OpState, just add an AdminState. We may need to keep OpState around for Fuji, but mark it as deprecated field, and then remove it in Geneva? I guess you could argue that since nothing actually uses ProvisionWatchers, removing it doesn't technically break the API.

As far as "OnMatch/IGNORE" goes, I'd like to see this as a separate issue. I'm not sure I understand the use case for it? If you want to IGNORE devices that match an ProvisionWatcher, delete it. During our previous conversation about blacklists it the suggestion was to add another field to the ProvisionWatcher which supports glob-style matching or regular expressions to declare an ignore pattern. This field would then be applied before or after the standard whitelist was applied. 

Let's discuss at the next meeting.

**Comment by iain-anderson** [comment]
Updated design as of Device WG meeting 1st July:

- Mark `OperatingState` field as deprecated
- Add new `AdministrativeState` field
- Add new `BlockingIdentifiers` field, typed as `map[string]string`

Notes:

1. Devices added via the PW mechanism will have their `AdministrativeState` set according to the value in the matching PW. The `OperatingState` for the new device will always be `ENABLED`.
2. The `BlockingIdentifiers` field is an optional set of key-value pairs which are to be matched against new devices in the same way as `Identifiers`, but a successful match in `BlockingIdentifiers` will cause the device to be **not** added.

**Comment by iain-anderson** [comment]
Additional proposals:
1. Make `BlockingIdentifiers` a map of slices, ie `map[string][]string`
Each string in the slice is then a literal value or pattern to block against.
2. Should the pattern-matching capabilities be limited to "*" characters or should we support more sophisticated matching?
Eg: shell-style globbing via Go's `filepath.Match` and C's `fnmatch()`

**Comment by iain-anderson** [comment]
Re suggestion 2 above: core-contracts does not necessarily need to be aware of the semantics of the matching string. However, the Java device services performed regex matching and I believe we should do the same in Go (regexp.CompilePOSIX) and C (regex.h)

**Comment by iain-anderson** [comment]
And for the other, I'd go for typing both `Identifiers` and `BlockingIdentifiers` as `map[string][]string`

**Comment by iain-anderson** [comment]
...except that that would be an API break. So just `BlockingIdentifiers`. New summary:

*   Mark `OperatingState` field as deprecated
*   Add new `AdminState` field
*   Add new `BlockingIdentifiers` field, typed as `map[string][]string`

Notes:

1.  Devices added via the PW mechanism will have their `AdminState` set according to the value in the matching PW. The `OperatingState` for the new device will always be `ENABLED`.
2.  The `BlockingIdentifiers` field is an optional map of identifiers to string slices which are to be matched against new devices in the same way as Identifiers, but a successful match in `BlockingIdentifiers` will cause the device to be not added. Each string in the slice is a potential blocking match.
3.  The match strings are to be interpreted as POSIX-style regexes.
4.  The `AdminState` type itself is now not to be modified.

**Comment by iain-anderson** [comment]
The changes identified in the previous comment [https://github.com/edgexfoundry/go-mod-core-contracts/issues/111#issuecomment-517362872](url) are agreed as of the device WG meeting 5th August.
