### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by dweomer** [edgexfoundry/go-mod-core-contracts#12]
In reviewing my changes for a downstream repo that refactored from `edgexfoundry/edgex-go` to `edgexfoundry/go-mod-core-contracts` I noticed that to keep the `Attribution.txt` consistent we would want a `LICENSE` file in this repo.

**Comment by anonymouse64** [comment]
Note that since this library doesn't actually ship any binaries and as such isn't distributed itself, it doesn't actually need an Attribution.txt file, just a LICENSE.

You only need Attribution.txt when you are shipping/delivering/redistributing code, this repo doesn't produce any artifacts and as such doesn't need an Attribution.txt.
