### ISSUE TITLE
Add Subscription Client for services to create notification subscriptions

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-core-contracts#158]
A service must first create a subscription before it can call the Notifications Client  SendNotification API.

Currently services are using a hard coded URL from configuration.

By adding the Subscription Client a service can create a notification subscription in the same manner it uses other Clients.

**Comment by AnthonyMBonafide** [comment]
As I am working through this I am seeing there are some complexities in what I am doing.

Firstly, I want to ensure that I am solving the correct problem. My understanding is that  --at a high level-- this issue is asking to implement a subscription client which contains functionality to allow users of the client to create subscriptions with `support-notifications` and propagate notifications from `support-notifications` back to the user of the client. Is that correct? 

If so, here is what I am facing:
1. We must create an HTTP server so that `support-notifications` can communicate back
1. Managing Certs for HTTPS(This is a client library so it is odd to ask the caller for a cert so that we are secure)
1. We must either manage ports or URIs to support multiple subscriptions to allow us to differentiate between notifications for different subscriptions.
1. Cleaning up resources

All of these are not difficult but require more effort then just a couple of HTTP calls, so I want to make sure my direction is clear before I move forward with this.

I hope this all makes sense.

As a side note, I created an issue to add support for another communication mechanism which is lightweight and takes the burden off off the subscriber. https://github.com/edgexfoundry/edgex-go/issues/2304

**Comment by AnthonyMBonafide** [comment]
^ @lenny-intel , @michaelestrin

**Comment by lenny-intel** [comment]
@AnthonyMBonafide , for our use cases we set up subscription to be able to send an email via the notification service. 

Here is the subscription setup code for one of our use cases that is now on public GitHub:
https://github.com/intel-iot-devkit/rtsf-at-checkout-reference-design/blob/d45ea1ee236274e18226aa408b793eca4d1191e3/rtsf-at-checkout-loss-detector/functions/notify.go#L87

We have to create this subscription to set the list of email addresses for when we send the notifications here:
https://github.com/intel-iot-devkit/rtsf-at-checkout-reference-design/blob/d45ea1ee236274e18226aa408b793eca4d1191e3/rtsf-at-checkout-loss-detector/functions/notify.go#L79

This type of subscription doesn't require a callback, so maybe this issue should be for create email notification subscription, which is the common type we have been using in our Use Cases.

**Comment by lenny-intel** [comment]
@AnthonyMBonafide , I also think this is a low priority issue compared to all the other things we want for Geneva.

**Comment by michaelestrin** [comment]
@AnthonyMBonafide based on @lenny-intel's feedback, let's drop this issue back into the icebox for now and focus on higher-priority Geneva work.

**Comment by AnthonyMBonafide** [comment]
@michaelestrin Sounds good.

@lenny-intel , thank you for the clarification. I was completely misunderstanding the issue.

**Comment by cloudxxx8** [comment]
this issue has been resolved in v2.0.0
all the client library is provided
