### ISSUE TITLE
Consider removal of DeviceProfile from Device struct

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/go-mod-core-contracts#27]
I recently reported an [issue](https://github.com/edgexfoundry/device-sdk-go/issues/202) against device-sdk-go that concerned dumping entire objects in non-debug log messages.

The offending log message was actually including the entire state of a Device object, which is enormous! This got me to thinking whether it's actually a good idea for us to be embedding an entire DeviceProfile in every device as opposed to DeviceProfile.Name? The device SDKs have a cache of device profiles, and to me, it would be much more efficient to always retrieve them from the cache instead of embedding them in every single device.

It also appears that the device-sdk-go [callback handler](https://github.com/edgexfoundry/device-sdk-go/blob/master/internal/handler/callback.go#L105) doesn't properly update every device in its device cache when a Profile is updated. It's also not clear who's responsible to update value descriptors if/when a DeviceProfile change occurs. It doesn't look like device-sdk-go currently handles this case.

Note - this is related to issue #40 which proposes removing DeviceService from Device.

**Comment by difince** [comment]
If you take the decision to make the Device struct lighter (and I think it is doable from DS point of view, at least I took a look of device.DeviceProfile struct) can I work on it? I think it is good issue for a newcomer. To resolve this issue a lot of places will need to be touched - giving a good overview and understanding of the project implementation.

**Comment by tsconn23** [comment]
@difince You are certainly welcome to give it a shot, however the teams are very focused on specific tasks leading to the Edinburgh deliverable right now. That means I can't promise you when a potential change might get pulled in. If you do decide to investigate this further, remember that this contract module is utilized by edgex-go, device-sdk-go and app-functions-sdk-go. In particular with those first two repos, I expect the above change will cause side effects that will also need to be addressed. As part of your work, if you don't mind, please try to document those side effects here as part of this issue because if we were to merge your change, we would then be committed to doing the integration work in the other repos.

For more context you're welcome to join the weekly [Device Service](https://wiki.edgexfoundry.org/display/FA/Device+and+Device+SDK+Working+Group) and [Core Working Group](https://wiki.edgexfoundry.org/display/FA/Core+Working+Group) calls.

**Comment by jduranf** [comment]
I completely agree with the idea, just some comments:
1. Will be fine if the equivalent change also it's done with Provision Watchers
2. This change shouldn't imply any problem in device-sdk-go. Currently in device-sdk-go only it's used the Device.Profile.Name. In fact, this change will help to reduce the device cache size.
3. In order to simplify this issue, I recommend to not allow change the device profile name if the device profile is in use. Also this will solve the issue commented by @tonyespy related with the callback system in device-sdk-go.
4. @tonyespy there is an issue related with [value descriptors](https://github.com/edgexfoundry/edgex-go/issues/1071), should be great to have your opinion

**Comment by tonyespy** [comment]
I've done some analysis, and it turns out there are two use REST endpoints in other services which rely on the Profile being included in a Device:

 * Core Command's **/device** endpoint returns one (or all) device and the available commands. Today, this relies on a function in `core-contracts/models/command_response.go` which just grabs the commands directly from the Profile embedded in the device. If we remove Profile from device, we should replace it with Profile.Name, get rid of this function in command_response.go, and make Core Data go directly to Core Metadata for the list of commands for a given device profile.

 * Core Data's **/valuedescriptor** endpoint allows querying by device ID or Name. A function called `AllAssociatedValueDescriptors()` in `core-contracts/models/device.go` grabs the Commands slice from the embedded Profile, and extracts the valuedescriptors from it. Note, I *think* this code is incorrect as implemented. Commands w/in the Profile define the value commands that someone can reference from Core Command. This is different than the set of commands supported by the device service itself. I need to do some more testing here, and will open a bug against edgex-go if this is indeed broken.

**Comment by tonyespy** [comment]
Here's some clarification to my last comment in which I said:

> Core Data's /valuedescriptor endpoint allows querying by device ID or Name. A function called AllAssociatedValueDescriptors() in core-contracts/models/device.go grabs the Commands slice from the embedded Profile, and extracts the valuedescriptors from it. Note, I think this code is incorrect as implemented.

This relates to the discussion we had in today's device service WG meeting. The first two sections of a device profile are deviceResources, and the to-be-named deviceCommands. When a profile is imported into Core Metadata by a device service (based on either SDK), the DS creates value descriptors in Core Data for each of its device resources (note - there is a global namespace for these names). These are not tied to any specific device or device resource in Core Data.

If you query all value descriptors from Core Data using the /valuedescriptor endpoint, it will list all of the value descriptors it has persisted to the db.

If however, you query the value descriptors of a specific device, using /valuedescriptor/devicename/{name} or /valuedescriptor/deviceid/{id}, then Core Data will lookup the device in Core Metadata, and only report back the value descriptors associated with commands from the command section of the device profile. Although this list is accurate if you're actually using the Core Command service, if you're instead only relying on AutoEvents, a client trying to interpret Readings won't be able to get the full list of value descriptor names if the device's profile doesn't provide coverage for all of it's device resources in the profile's command section. In other words, if a device profile contains no commands, and you query Core Data for its value descriptors, you'll get an empty list even though the device profile actually contains one or more device resources.

Ex.

devResources:
 "resource1"
 "resource2"
resources:
  "GetAll"

**Comment by michaelestrin** [comment]
Closed.  Expect this to be addressed by the [Geneva v2 API](https://github.com/tsconn23/edgex-geneva-api) changes.
