### ISSUE TITLE
[V2] Make valueType case insensitive and covert to PascalCase internally

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#383]
It will be easier to compare the string

**Comment by tonyespy** [comment]
@cloudxxx8 please see the discussion in issue #289. Maybe we need one last discussion? If so let's add to this week's Core WG agenda.

**Comment by iain-anderson** [comment]
@tonyespy @cloudxxx8 Core WG is off this week :)
I think we have a couple of choices to make. Firstly, either
1) Always validate case-insensitive on type names
2) Validate case-insensitive for Request objects but convert to the case-correct constants. Then we can validate case-sensitive for Response objects

Secondly, use mixed-case or lower-case for the constants?

Am happy to go with whatever makes for straightforward implementation tbh

**Comment by tonyespy** [comment]
@iain-anderson thanks for your comments, since we're not having a core WG meeting this week, I'll punt it back to you, and we can discuss at our next Devices WG next week.

My preference would be to validate case-insensitive on incoming requests (or messages) and then convert to preferred case in needed. I also think that although the original specification(s) called for lowercase type constants, we've been publishing readings to the message bus with CamelCase for a few releases now, and to change this would mean one more breaking change for 2.0, so my preference would be to leave them "as is".
