### ISSUE TITLE
[V2] Create a common Address struct for different endpoint protocols

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/go-mod-core-contracts#523]
We need endpoint information, for example REST or MQTT, in different services, such as support-notifications and support-scheduler.
It would be better to create a common struct for them.
The initial design would be the structure like Reading.
BaseAddressable: a base struct contains the common fields, such as type, host, port, and so on.  SecretPath related fields could be added here once we support security connection.
RESTAddressable: REST specific struct contains httpMethod, queryParameters, and so on.
MQTTAddressable: MQTT specific struct contains topic, publisher, and so on.
Addressable: an interface could be converted to RESTAddressable or MQTTAddressable according to the type field.

**Comment by jpwhitemn** [comment]
Since App Services also have to communicate via REST and MQTT (sometime secured and sometimes insecure), is there some commonality we can get from these services?  I would like to see the configuration be similar in both so as not to confuse the user.  @lenny-intel - is what is in app services something that could be harvested?

**Comment by lenny-intel** [comment]
@jpwhitemn , similar thoughts have been going through my mind once this came up. Note that this is a sub-DTO to combined common information for the V2 APIs. I am not sure how applicable it is to configuration.  The proposed implementation uses inline structs which we `can not` use for configuration since it isn't supported by the consul modules we use.

**Comment by cloudxxx8** [comment]
I don't think it is necessary to re-use this in the configuration model.
