### ISSUE TITLE
Add the http clients/dtos of KVS and registry for Keeper

### ISSUE THREAD

**Issue by jackchenjc** [edgexfoundry/go-mod-core-contracts#873]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for core-keeper
https://github.com/edgexfoundry-holding/edgex-core-keeper/tree/edgex-go-v3.2.0-dev.10

### Description [**REQUIRED**]
 Add the http clients/dtos of KVS (key-value APIs) and registry for Keeper

**Comment by lenny-intel** [comment]
Support for Keeper should be isolate in go-mod-configuration and go-mod-registration. Please do not create a dependency on core-contracts in these other packages.

@cloudxxx8 , FYI

**Comment by cloudxxx8** [comment]
@lenny-intel you are right, and we will try to avoid adding dependencies.
@jackchenjc please see if you can move dtos and client code to go-mod-configuration and go-mod-registration.

**Comment by cloudxxx8** [comment]
@lenny-intel after some code investigation, I just remembered the purppose we add code (clients / dtos) to go-mod-core-contracts is for edgex-go only.  It won't add any new dependencies in go-mod-configuration and go-mod-registry.
Since the main code base of core-keeper is in the mono repo edgex-go, it needs DTOs for the REST API implementation and reuse some common DTOs like `common.BaseRequest`.
You can confirm that once the PR is opened.
